### ISSUE TITLE
cannot import makeGetSet with vitest

### ISSUE THREAD

**Issue by poor666** [moment/moment#6254]
**Describe the bug**
After upgrading to 2.30.1 im getting a `TypeError: makeGetSet is not a function` when import the moment.js in a test using vitest.

```
cat node_modules/moment/package.json | grep version
"version": "2.30.1",
```

**To Reproduce**
```
import { test, assert, describe } from 'vitest';
import { formatDistanceTimeInWords } from '../src/modules/formatters.js';

import moment from 'moment/src/moment.js';

describe('modules/formatters.js', () => {
  test('formatDistanceTimeInWords', () => {
    const futureDate = moment().add(8, 'days');
    const value = formatDistanceTimeInWords(futureDate);
    assert.equal(value, 'Expira in 8 days');
  });
});


```

**Output**
```
yarn vitest run test/dates.test.js
yarn run v1.22.22

 ❯ test/dates.test.js (0)

⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯ Failed Suites 1 ⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯

 FAIL  test/dates.test.js [ test/dates.test.js ]
TypeError: makeGetSet is not a function
 ❯ node_modules/moment/src/lib/units/year.js:73:40
     71| export var getSetYear = makeGetSet('FullYear', true);
     72|
     73| export function getIsLeapYear() {
       |                                        ^
     74|     return isLeapYear(this.year());
     75| }
 ❯ node_modules/moment/src/lib/moment/get-set.js:5:31
```

**With other versions its ok.**

```
cat node_modules/moment/package.json | grep version
    "version": "2.29.4",

yarn vitest run test/dates.test.js
yarn run v1.22.22
$ /Users/joaoramos/work/sideproject/web-ui/node_modules/.bin/vitest run test/dates.test.js

 RUN  v1.2.1 /Users/joaoramos/work/sideproject/web-ui

 ✓ test/dates.test.js (1)
   ✓ modules/formatters.js (1)
     ✓ formatDistanceTimeInWords

 Test Files  1 passed (1)
      Tests  1 passed (1)
   Start at  18:42:59
   Duration  235ms (transform 93ms, setup 0ms, collect 116ms, tests 2ms, environment 0ms, prepare 32ms)

✨  Done in 0.73s.
```

All tests with vitest 1.2.1

```
yarn vitest -v
yarn run v1.22.22
$ /Users/joaoramos/work/sideproject/web-ui/node_modules/.bin/vitest -v
vitest/1.2.1 darwin-arm64 node-v22.4.0
✨  Done in 0.40s.
```

**Comment by mattjohnsonpint** [comment]
The problem is how you are importing Moment.

You have:

```js
import moment from 'moment/src/moment.js';
```

You should instead use:

```js
import moment from 'moment';
```
