### ISSUE TITLE
[TypeScript] "error TS2304: Cannot find name 'moment'" when used with "module":"none"

### ISSUE THREAD

**Issue by rossipedia** [moment/moment#3763]
Typescript seems to not be able to resolve the global `moment()` function when used in a non-module context.

tsc version: 2.1.6
moment version: 2.17.1

Repro (assuming `tsc` is on your `$PATH`):

``` bash
$ mkdir repro && cd repro
$ npm i moment
$ echo 'const now = moment();' > test.ts
$ tsc --module none test.ts
test.ts(1,13): error TS2304: Cannot find name 'moment'.
```

However, using a module type works as expected:
``` bash
$ echo 'import * as moment from "moment"; const now = moment();' > test2.ts
$ tsc --module commonjs test2.js
```

Unfortunately, my project does not use a bundler or module system, so I'm stuck with `"module": "none"` for now. 

Is my only alternative to use something like `typings install --save --global dt~moment` ?

**Comment by alexdresko** [comment]
I'm facing the same problem. It doesn't matter what module type you specify in tsconfig.json. I get the same error as @rossipedia

**Comment by zVolodymyr** [comment]
I reported same issue (https://github.com/moment/moment/issues/3663), but unfortunately it was just closed.

**Comment by alexdresko** [comment]
I ended up copying `moment.d.ts` into my `/scripts/app` directory and implemented the fix specified in https://github.com/moment/moment/issues/3663#issuecomment-273199291

Hopefully a more permanent fix will make its way into `moment.d.ts` eventually.

**Comment by kamek-pf** [comment]
I solved this by specifying `"moduleResolution": "node"` in my tsconfig. Not sure if this is an option for you guys, but it seems to do the trick.

**Comment by rossipedia** [comment]
`"moduleResolution": "node"` did not fix it for me, unfortunately

**Comment by alexdresko** [comment]
@rossipedia Me either.

**Comment by czb** [comment]
Would it not help to add `export as namespace moment;` into d.ts file?

https://github.com/moment/moment/issues/3808

**Comment by rossipedia** [comment]
@czb that also did not fix the issue for me, unfortunately :(

**Comment by mtgibbs** [comment]
I've resolved this using a couple of hacks that others have mentioned around a ton of issues in lots of projects that are having this problem.  Just wrap it up in a custom definition file of your own.  This is using Typescript 2.2.

tsconfig.json
```json
"compilerOptions": {
    "target": "ES5",
    "moduleResolution": "node",
    ...
}
```

moment.custom.d.ts
```typescript
import * as _moment from 'moment';
export as namespace moment;
export = _moment;
```

**Comment by rossipedia** [comment]
I'm curious as to why that doesn't work when that code is added directly to `moment.d.ts`? I can't help but think we're butting into some obscure TypeScript resolution bug, and unfortunately `tsc` doesn't have a verbose mode (that I know of) that would help pinpoint where things are going wrong.

**Comment by czb** [comment]
I think that if you define `"module": "none"` typescript does not look for `d.ts` files under the `node_modules/moment` folder. My experience is that it is only looking under the `node_modules/@types` folder. So there are basically these options. 

1. Copy `moment.d.ts` under `node_modules/@types/moment`
2. Include `/// <reference path="./node_modules/moment/moment.d.ts" />` into your `.ts` file
3.  Call `tsc --typeRoots node_modules test.ts`
4. Put the `./node_modules/moment/moment.d.ts` into `files` section of `tsconfig.json`

**You also need to add `export as namespace moment;` into the `moment.d.ts` file.**

**Comment by marwahaha** [comment]
the Moment team would love any PRs that would fix this, but stay TS 1.x compatible.

**Comment by rossipedia** [comment]
I still have yet to find a solution that works at all, but when I do I'll be sure to add a PR

**Comment by cg-cnu** [comment]
According to #3663 the temporary fix to get it working without any bundler... 

* Copy ``moment.d.ts`` from ```node_modules/moment/```  to ```node_modules/@types/moment```

* Change ``export = moment;`` in ``moment.d.ts``  to
```
declare module "moment" {
    export = moment;
}
```
* Rename ```moment.d.ts``` to ```index.d.ts```

Just use moment and your editor( in my case vscode ) and tsc shouldn't complain

**Comment by evanjmg** [comment]
+1 please fix this

**Comment by elSteeze** [comment]
@mtgibbs Where are you putting the moment.custom.d.ts file? Is there any other configuration that needs to happen for your app to find this custom.d.ts file?

**Comment by mtgibbs** [comment]
@elSteeze 

Yeah, I'm adding them to my `tsconfig.json`.  Here's a scrubbed example:

```
{
  "compilerOptions": {
    "target": "ES5",
    "moduleResolution": "node",
    "typeRoots": [
      "./node_modules/@types"
    ]
  },
  "compileOnSave": true,
  "exclude": [
    "node_modules",
    "./path/to/typings/**/*.d.ts",
    "./typings"
  ],
  "include": [
    "./path/to/typings/vue.custom.d.ts",
    "./path/to/typings/moment.custom.d.ts",
    "./path/to/src/**/*.ts"
  ]
}
```

**Comment by elSteeze** [comment]
@mtgibbs Hey thanks man! Appreciate the speedy reply. I'll give that a try.

**Comment by elSteeze** [comment]
@mtgibbs Sorry for another noob like question, after implementing your solution I started getting editor errors on the moment keyword in my ts code...

`'moment' refers to a UMD global, but the current file is a module. Consider adding an import instead`

I did some personal research and attempted to implement a solution by rewriting moment.custom.d.ts but unfortunately, that didn't fix my issue.

Sorry, not trying to be one of those pesky dev's who makes everyone else debug their code, I'm a recent grad and I'm new to working with 3rd party libraries in an Angular 2 environment

Here is my updated module.custom.d.ts

```javascript
declare var moment: any;
declare var module: NodeModule;
interface NodeModule {
    id: string;
}
import * as _moment from 'moment';
export as namespace moment;
export = _moment;
```

**Comment by mtgibbs** [comment]
No problem. If you're using Angular 2 you should be on 2.0+ TS. I don't work in Angular so I'm unsure. Mind pasting what you can of your tsconfig.json and I'll take a look after I get back to a real computer.

**Comment by elSteeze** [comment]
Sure!

This is my entire tsconfig.es5.json file inside the src directory of my angular 2 module I'm building.
I appreciate the help by the way

```typescript
{
  "compilerOptions": {
    "declaration": true,
    "module": "es2015",
    "target": "es5",
    "baseUrl": ".",
    "stripInternal": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "moduleResolution": "node",
    "outDir": "../build",
    "rootDir": ".",
    "lib": [
      "es2015",
      "dom"
    ],
    "skipLibCheck": true,
    "typeRoots": [
      "./node_modules/@types"
    ]
  },
  "compileOnSave": true,
  "exclude": [
    "node_modules",
    "./typings/**/*.d.ts",
    "./typings"
  ],
  "include": [
    "./typings/moment.custom.d.ts",
    "./src/**/*.ts"
  ],
  "angularCompilerOptions": {
    "annotateForClosureCompiler": true,
    "strictMetadataEmit": true,
    "skipTemplateCodegen": true,
    "flatModuleOutFile": "new-version-library.js",
    "flatModuleId": "new-version-library"
  },
  "files": [
    "./index.ts"
  ]
}

```

**Comment by mtgibbs** [comment]
What version of TS are you compiling in? You should just be able to import moment at the top without my hack.

**Comment by elSteeze** [comment]
@mtgibbs I'm using v2.2, and that's what I thought. Unfortunately, it's not working. I'm almost at the point where I write my own version of the functionality we're taking from momentjs, because I can't seem to get this working.

**Comment by mtgibbs** [comment]
@elSteeze 

Ok, going back here.  I noticed that you said that you've made a custom `module.custom.d.ts`, but then you refer to my `moment.custom.d.ts` in your `tsconfig.json`.  Make sure that you've made `moment.custom.d.ts` and added it to your compiler, none of that extra stuff that you had declaring it things.  Then make sure that you're referencing it at the top of the file you're wanting to use it in.

```ts
/// <reference path="path/to/your/moment.custom.d.ts" />
```
This should allow you to reference it as a global variable like in my original workaround.

**Comment by elSteeze** [comment]
Awesome thank you @mtgibbs ! I really do appreciate the help. 
Cheers mate!

**Comment by ShawnTalbert** [comment]
This works for me:

* comment out `// export = moment` in the official .d.ts file
* add 'node_modules/moment/moment.d.ts` to `tsconfig.json`

Alternately, copy the modified `moment.d.ts` to a location of your choice and add the path to it in your `tsconfig.json`

I think the main problem is that when explicitly using `"module":"none"` in tsconfig.json you can't have any top level import or exports in any libraries. Hence the default moment

**Comment by gyanchandk** [comment]
you have to first import in component as
import *  as moment from "moment";

it worked well for me

**Comment by eman1986** [comment]
I applied what mtgibbs did but I get the following message:

> TS2686: 'moment' refers to a UMD global, but the current file is a module. Consider adding an import instead.

any ideas on how to fix that

**Comment by darek8686** [comment]
Why don't you fix this issue? It is very important.

**Comment by AmirTugi** [comment]
Adding `"module": "commonjs"` fixed it for me

**Comment by darek8686** [comment]
But i have to use `"module": "none"`. Commonjs is not a solution.

**Comment by rossipedia** [comment]
If I'm understanding it correctly, this will be resolved with [TypeScript 2.9's import types](https://github.com/Microsoft/TypeScript/issues/14844) feature, which will allow `import`ing type definitions without affecting the the module / ambient context.

**Comment by Ciantic** [comment]
I'm using TS 3.0.1, is this now solved? It doesn't work out of the box at least.

**Comment by rossipedia** [comment]
TS 3.0.1 seems to fix this issue (and it's been open for over a year and a half with no traction)

**Comment by njaineworkplaceapps** [comment]
Hi rossipedia,
I am facing same issue in angular-6 project. As per your comments it's resolved in TS 3.0.1 but angular6 CLI doesn't support TypeScript version 3.0.1.

Can you please help to resolve this issue?

**Comment by RudeySH** [comment]
Did anyone else also encounter the `@types/moment` npm package which is just a stub and tells you to use the file that's provided by the normal moment package?

... Why does moment have to differently compared to every other package? This is the reason why this issue exists, and thousands of hours were spent by developers struggling with this.

Sure, @Ciantic's solution works in TS 3.0.1, but I don't have to use something `declare var moment: typeof import("moment");` for any of the other packages I'm using.

**Comment by zVolodymyr** [comment]
It doesn't look like Typescript 3.0.1 fix that issue, it looks like it just give us workaround.

**Comment by RudeySH** [comment]
>it looks like it just give us workaround.

Yup, it's exactly this. This is not an acceptable "fix".

It's only been a day and I just realized that the TS 3.0.1 workaround only imports the `moment` function, not the namespace/types. So if you want to pass a moment object into a function, this happens:

![image](https://user-images.githubusercontent.com/3918757/49186829-f7d55580-f365-11e8-9d1b-0434598c191f.png)

Please reopen this issue, or better: fix the .d.t.s file.

**Comment by pspi** [comment]
Specifying the following in tsconfig.json fixed it (typescript 3.3.3 and moment 2.24.0)

```
{
  "compilerOptions": {
    "module": "commonjs"
  }
}
```

**Comment by rossipedia** [comment]
I'm no longer using moment for much these days, but I'm happy to re-open the issue if it's still valid.

**Comment by nagipogu** [comment]
ERROR in src/app/services/get-list.service.ts(22,54): error TS2304: Cannot find                             name '_'.
--


what is the solution for this??

**Comment by i-cant-git** [comment]
@nagipogu No solution for that, this issue is for [moment.js](https://momentjs.com/), please open your issue in [underscore.js's Github repository](https://github.com/jashkenas/underscore).

**Comment by mkay581** [comment]
I'm running into this issue with latest version of moment with latest version of TS. Does anyone have any successful workaround?

**Comment by dko-slapdash** [comment]
Still not working, the solution for me was to `yarn add -W moment@2.22.1`.

When I installed the latest moment version and looked into node_modules/moment/package.json, I saw this: https://github.com/moment/moment/blob/develop/package.json#L29 - but there was no existing directory `node_modules/moment/ts3.1-typings`, so it's not surprising TS coudln't find it. I think there may be some bug with an installation script (or a package) or so. Yes, we have `"module": "esnext"` in tsconfig.json.

**Comment by Scharkee** [comment]
For me it broke with 2.25.0:

I used pnpm add moment@2.24.0 as a temporary workaround.

**Comment by anouarattn** [comment]
> For me it broke with 2.25.0:
> 
> I used pnpm add moment@2.24.0 as a temporary workaround.

work good, thank you

**Comment by barryguda-1** [comment]
> 
> 
> For me it broke with 2.25.0:
> 
> I used pnpm add moment@2.24.0 as a temporary workaround.

Same here added it to : "dependencies" {"moment": "^2.24.0",
}...seems to work thank you.

**Comment by joshuakeel** [comment]
Downgrading to 2.24.0 also worked for me. Looks like a regression in 2.25.0.

**Comment by marwahaha** [comment]
Does 2.25.3 fix your issues?

There are so many different types of situations where Moment.js is used, let alone TS 1.x, TS 2.x, TS 3.x...
I am hesitant to make changes that break any group of these users.

If you think the documentation can be improved, please post at https://github.com/moment/momentjs.com/

**Comment by ralftar** [comment]
> Does 2.25.3 fix your issues?

Yes.

Rolled back to 2.24.0 when 2.25.1 failed for me in Angular 9. With 2.25.3 it's back on track again.

**Comment by marwahaha** [comment]
Ok, great. I will close for now.

Please re-open (or open a new issue) if you still have concerns.

**Comment by giovannipds** [comment]
I lost a lot of time trying to solve a type problem and @oldrich-s comment of `include` was very useful! Thanks very much.

**Comment by ashkan-dev-86** [comment]
> Would it not help to add `export as namespace moment;` into the `moment.d.ts` file?
> 
> See: #3808

You shouldn't do that.
Because in case of reinstalling, this will reset to its default.
