### PR TITLE
[feature] TypeScript: Expose type definitions to plain .js files lacking any imports

### PR DESCRIPTION
**Pull request by davidfstr**
It is now possible to use the `moment` global from a .js file and have TypeScript typecheck that .js file without complaining.

Test case:

```
# (npm install developer version of "moment" with this change)
$ npm install typescript
$ echo 'document.querySelector("body").textContent = moment().toString();' > index.js
$ node_modules/.bin/tsc --allowJs --checkJs --noEmit index.js
# (no errors)
```

Without this change, you would receive the errors:

```
index.js:1:46 - error TS2304: Cannot find name 'moment'.

1 document.querySelector("body").textContent = moment().toString();
                                               ~~~~~~
Found 1 error.
```

### CODE REVIEW

**Comment by davidfstr** [comment]
I revised the commit title to conform to the Title check that you have, although GitHub still tells me the Title check is failing.

**Comment by davidfstr** [comment]
This patch still needs some work: One of the unit tests is failing:

```
$ node_modules/.bin/tsc --project typing-tests
node_modules/@types/node/index.d.ts(214,41): error TS2304: Cannot find name 'Promise'.
# (many similar errors)
```

I did not upgrade the version of `@types/node` and tsc wasn't giving this failure before, so perhaps the new version of tsc is being more strict with its checks.

**Comment by davidfstr** [comment]
Everything passes now except the title check. Know how to fix it?

I last attempted to amend and rebase the offending commit but that didn't seem to make the title check happy.

**Comment by davidfstr** [comment]
Apparently the title check was referring to the PR and not the commit. Recommend adjusting the check's message to be more clear about that.

**Comment by davidfstr** [comment]
Any reviewers familar with TypeScript available to take a look at this PR?

File: typing-tests/tsconfig.json [hunk 1]
```diff
@@ -1,12 +1,15 @@
 {
   "compileOnSave": false,
   "compilerOptions": {
+    "target": "es6",
```
Comment (simonhaenisch) [inline typing-tests/tsconfig.json]: Instead of targeting `es6` (which means native promise support is expected), maybe it would be better to add `"lib": ["es2015"]` (which will make promises work for `es3` and `es5` targets).

Comment (davidfstr) [reply typing-tests/tsconfig.json]: Agreed. Done.

**Comment by davidfstr** [comment]
@marwahaha You appear to be the only active committer on the Moment project since 1/1/2019.

Is there anything I can help you with in getting this PR merged? Perhaps an unresolved concern. Perhaps a squash of all changes to one commit.

**Comment by davidfstr** [comment]
While waiting for this PR to be merged, I've documented a workaround in the following StackOverflow answer: https://stackoverflow.com/a/57263931/604063

**Comment by davidfstr** [comment]
@simonhaenisch you are marked as the reviewer of this issue, but have taken no activity within the last month. If you do not have bandwidth, could you unassign yourself?

I'm guessing setting a blank reviewer will put this back into a to-be-reviewed pool. However I am unable to locate documentation for how the Moment project's maintenance process works, so I am not 100% sure. Regardless I care about this ticket moving forward and so I will do my best to follow my best guess of the process.

**Comment by simonhaenisch** [comment]
I’m not a maintainer, nor assigned to the PR... I just left a code review comment, because I also care about this going forward.

**Comment by davidfstr** [comment]
Aye, and thank you for the comments @simonhaenisch.

I suppose I'll just leave this ticket around then. Nothing obvious I can do currently to move it forward myself.

**Comment by ichernev** [comment]
@davidfstr the current version of moment supports typescript 1.x. Maybe in next major we can bump this.

**Comment by davidfstr** [comment]
Is the ask that I check back later, perhaps in a year, to ask whether Moment has upgraded its TypeScript support, and then reopen this issue, if it’s not resolved by the upgrade?
