### ISSUE TITLE
TS2307: Cannot find module 'moment'. 

### ISSUE THREAD

**Issue by gayankasun** [moment/moment#5486]
I m having issue with importing moment in to my angular 8 project.

Angular version = 8.3.26
Type script version = 3.6.2
moment version = 2.25.0

i'm getting error **TS2307: Cannot find module 'moment'.** and i have used 
**import moment from 'moment';** . 

i have add **"moduleResolution": "node"** and **"allowSyntheticDefaultImports": true,** in tsConfig

can any one help on this

**Comment by codebrent** [comment]
try version 2.24, my tests started to fail on new version but fine with previous

**Comment by gayankasun** [comment]
> try version 2.24, my tests started to fail on new version but fine with previous

I have tried. but same error came.

**Comment by codebrent** [comment]
what does the line for moment in package.json look like?

**Comment by acharyaks90** [comment]
its working with 2.24.0  may be deployment error in 2.25.0 
Please deploy the new version with fix.

**Comment by rilyu** [comment]
if you use yarn, add  resolutions block to package.json to override versions of sub-dependency, it work for me
```
  "resolutions": {
    "moment": "2.24.0"
  }
```

**Comment by v1shva** [comment]
Seems that Typescript module resolution can't find moment. Using a relative path works ./node_modules/moment/moment. @codebrent Thanks, it's now working with 2.24.0 version.

**Comment by jafin** [comment]
In 2.25 this has been added to package.json.  But if I understand no corresponding location exists for the typedef file. Perhaps this broke the typings?
```json
"typesVersions": {
    ">=3.1": {
      "*": [
        "ts3.1-typings/*"
      ]
    }
  },
```

**Comment by gayankasun** [comment]
> its working with 2.24.0 may be deployment error in 2.25.0
> Please deploy the new version with fix.

No its not working for me

**Comment by gayankasun** [comment]
> what does the line for moment in package.json look like?

"moment": "^2.25.0",

>

**Comment by gayankasun** [comment]
![Capture](https://user-images.githubusercontent.com/5936088/80787308-cc324c80-8ba3-11ea-89b6-c4f3ef236457.PNG) 
All moment imports returning error

**Comment by gayankasun** [comment]
> what does the line for moment in package.json look like?

![111](https://user-images.githubusercontent.com/5936088/80787441-30551080-8ba4-11ea-8f9c-1500d2e4e769.PNG)

**Comment by codebrent** [comment]
try changing to "moment": "2.24.0", make sure that there isn't a ^ in it. delete node_models and re npm install. also if you have package-lock.json you may need to delete it. Otherwise npm will keep installing 2.25

**Comment by mthmulders** [comment]
I'm seeing the same issue, and according to the [Dependabot Compatibility score for moment](https://dependabot.com/compatibility-score/?dependency-name=moment&package-manager=npm_and_yarn&previous-version=2.24.0&new-version=2.25.0), I'm not the only one.

Downgrading to 2.24.0 may be a a work-around, but it effectively prevents at least some users from using 2.25.0.

**Comment by afenrir** [comment]
> try changing to "moment": "2.24.0", make sure that there isn't a ^ in it. delete node_models and re npm install. also if you have package-lock.json you may need to delete it. Otherwise npm will keep installing 2.25

The safer, canonical way to do this is simply `npm install moment@2.24.0`. You do not need to delete anything or change anything manually. 

I can confirm that downgrading to 2.24 fixes the issue.

**Comment by gayankasun** [comment]
In locally its running after down grade to  . but when i deploy this to Azure to its giving same error.
![azure error](https://user-images.githubusercontent.com/5936088/80791273-cf7f0580-8bae-11ea-9994-6af90bf7dbb6.PNG)

My question is if it is same **package.json** running both local and azure. 


> > try changing to "moment": "2.24.0", make sure that there isn't a ^ in it. delete node_models and re npm install. also if you have package-lock.json you may need to delete it. Otherwise npm will keep installing 2.25
> 
> The safer, canonical way to do this is simply `npm install moment@2.24.0`. You do not need to delete anything or change anything manually.
> 
> I can confirm that downgrading to 2.24 fixes the issue.

In locally its running after down grade to 2.24.0 . but when i deploy this to Azure to its giving same error.
![azure error](https://user-images.githubusercontent.com/5936088/80791348-01906780-8baf-11ea-8ab0-6cdc09bd6023.PNG)


My question is if it is same **package.json** running both local and azure.  i have attached error log in server

**Comment by shernshiou** [comment]
I can confirm 2.25.0 give this issue but not at 2.24.0.

**Comment by ijgithub** [comment]
I also confirm that 2.25.0 give this issue. Moment 2.24.0 works fine.

I experienced this problem during docker image build.

**Comment by leafqi** [comment]
its not working with 2.24.0 for me

**Comment by miluxmilux** [comment]
Downgrading fixed the issue here too. Maybe the TypeScript version may play a role in having the bug or not?

**Comment by zhuyuedlut** [comment]
I use moment-timezone
Its not working with fixing moment version to 2.24.0 in package.json

**Comment by Poyoman39** [comment]
> its not working with 2.24.0

you probably did not downgrade to 2.24.0. Remove your package-lock file and node_modules folder, then run this command :

> npm install --save --save-exact moment@2.24
> npm install

**Comment by simoami** [comment]
I'm also experiencing the same issue in a typescript project and the build is failing all of a sudden because we didn't pin the dependency in package.json.
```
error TS2307: Cannot find module 'moment'.
error Command failed with exit code 2.
```

pinning the version to `"2.24.0"` fixes the issue.

**Comment by abhinavsingi** [comment]
Can try with resolutions field in package.json

Add



> "resolutions": {
>     "moment": "2.24.0"
> }

**Comment by galaxyfeeder** [comment]
I also confirm that with 2.25.0 I have the same issue with typescript 3.8.3 and running with ts-node 8.9.1. Downgrading to 2.24.0 solved the problem.

**Comment by leafqi** [comment]
> @zhuyuedlut @leafqi
> 
> > its not working with 2.24.0
> 
> you probably did not downgrade to 2.24.0. Remove your package-lock file and node_modules folder, then run this command :
> 
> > npm install --save --save-exact moment@2.24
> > npm install

thx. my problem has been solved. its working with 2.24.0
correct usage
``` "moment": "2.24.0" ```
wrong usage
```  "moment": "^2.24.0"  ```

**Comment by shanmuganathanvel** [comment]
"moment": "2.24.0" is working for me also..

**Comment by tomfordweb** [comment]
Same, locking in 2.24.0 fixed it.

This is on an angular 7.2 app built with webpack ^4.2.0

**Comment by kumar-sanjeet1** [comment]
Yes,  2.24.0 is working fine. Does anyone know what is the change they've made?

**Comment by azalpacir** [comment]
Same, issue got fixed by setting fixed version to "2.24" instead of "^2.24"

**Comment by andrewstec** [comment]
Do we have an ETA for this fix? 

It's Friday and I am wondering if I should downgrade to 2.24.0 before the weekend.

**Comment by ArunKumar-Annamalai** [comment]
> try changing to "moment": "2.24.0", make sure that there isn't a ^ in it. delete node_models and re npm install. also if you have package-lock.json you may need to delete it. Otherwise npm will keep installing 2.25

Issue got fixed by downgrading the version to 2.24.0

**Comment by andrewstec** [comment]
> > try changing to "moment": "2.24.0", make sure that there isn't a ^ in it. delete node_models and re npm install. also if you have package-lock.json you may need to delete it. Otherwise npm will keep installing 2.25
> 
> Thanks. Issue got fixed by downgrading the version to 2.24.0

You are no longer living in the moment though :)

**Comment by ArunKumar-Annamalai** [comment]
> try changing to "moment": "2.24.0", make sure that there isn't a ^ in it. delete node_models and re npm install. also if you have package-lock.json you may need to delete it. Otherwise npm will keep installing 2.25

Thanks, Issue got fixed by downgrading version from 2.25.0 to 2.24.0. Also I did "^2.24.0" to "2.24.0"

**Comment by Unkn0wn0x** [comment]
If the downgrade von `2.25.0` to `2.24.0` does not work and you get the same error again, try to uninstall the module completely and re-install it again.

Using npm:
1. `npm uninstall moment`
2. `npm install moment@2.24.0`

Hope it helps.

Cheers
Unkn0wn0x

**Comment by J1445** [comment]
Any Idea when the fix will be released ?  I see this is a broken issue and I don't have access to make changes in Master to set the moment version to 2.24 now and production builds is failing left and right. 
Please share release ETA thanks

**Comment by WaseemRakab** [comment]
I had this issue also, and i fixed it
by removing those lines
`  "typesVersions": {
    ">=3.1": {
      "*": [
        "ts3.1-typings/*"
      ]
    }
  },`
lines 150-156
in
.\node_modules\moment\package.json

**Comment by azalpacir** [comment]
> I had this issue also, and i fixed it
> by removing those lines
> ` "typesVersions": { ">=3.1": { "*": [ "ts3.1-typings/*" ] } },`
> lines 150-156
> in
> .\node_modules\moment\package.json
> and after i did this, it's working completely fine with version 2.25

this will work locally, but for CI pipelines, I doubt

**Comment by sandman45** [comment]
Thanks everyone :D 2.24.0 worked for me as well..

**Comment by flowck** [comment]
Downgraded to `2.24.0`, and it's working fine.

**Comment by ichernev** [comment]
2.25.1 released

**Comment by mistermjtek** [comment]
Tested 2.25.1, issue still occurs.

**Comment by WaseemRakab** [comment]
Tested 2.25.1 , issue is gone. Thanks

**Comment by andrewstec** [comment]
Yeah, I tested this too and didn't experience any issues.

**Comment by mike-marcacci** [comment]
Indeed, upgraded minutes after it was published and all is well: thanks for the speedy fix!

**Comment by gayankasun** [comment]
Finally it works for me. downgrading to 2.24.0 working. but make sure to put "**moment": "2.24.0"**
instead of **"moment": "^2.24.0"**
![azure error](https://user-images.githubusercontent.com/5936088/80853208-6fd73780-8c4c-11ea-895c-d6162c1bff88.PNG)

**Comment by darwintnt** [comment]
version 2.25.1 solved the Cannot find module 'moment' problem, but I am testing in an Angular 8 application and it throws the following error:
```
WARNING in ./node_modules/moment/src/lib/locale/locales.js
Module not found: Error: Can't resolve './locale' in '/home/project/node_modules/moment/src/lib/ locale', has anyone else experienced this failure?
```

**Comment by jzrandall** [comment]
I'm also getting warnings in 2.25.1 about some of the other functions I'm referencing:
```
"export 'utc' (imported as 'moment') was not found in 'moment'
"export 'max' (imported as 'moment') was not found in 'moment'
"export 'min' (imported as 'moment') was not found in 'moment'
```

**Comment by Coding-Kiwi** [comment]
For me it was
```
    "moment": "2.24.0",
    "moment-timezone": "^0.5.31",
```

**Comment by quizdeveloper** [comment]
I think you can update moment to version 2.29.0

`
npm uninstall moment`
`npm install moment@2.29.0`

[TS2307: Cannot find module 'moment' in Angular 8](https://quizdeveloper.com/faq/ts2307-cannot-find-module-moment-in-angular-8-aid71)

**Comment by novelmedicare** [comment]
npm install moment --save

**Comment by xgqfrms** [comment]
```js
// import moment from "moment";
import * as moment from 'moment'

```

https://stackoverflow.com/questions/61537526/typescript-error-cannot-find-module-moment
