### ISSUE TITLE
Unable to mock timezone in latest package

### ISSUE THREAD

**Issue by davallen** [moment/moment#5918]
In previous version of moment library 2.22.2 I was able to mock out timezone in the jest.setup.js file as below. 
```
import moment from 'moment-timezone';
// the timezone in jest land is UTC
moment.tz.setDefault('UTC');
moment.tz.guess = () => 'UTC';
jest.mock('moment', () => {
    const actual = require.requireActual('moment');
    actual.fn.local = function () {
        // all times in jest land are already in local time
        return this;
    };
    actual.now = function () {
        // in jest land, the current time is always 6:30:0.0 PM, 5/27/2018 UTC
        return Date.UTC(2018, 4, 27, 18, 30, 0, 0);
    };
    // the remaining rules of time still apply in jest land
    return actual;
});
```
With latest package (2.29.1) this code no longer works and the timezone is no updated. Has the behavior changed within these packages? 

**Expected behavior**
I would expect the behavior to not have changed.

**Comment by marwahaha** [comment]
@ellenaua  ?

**Comment by mattjohnsonpint** [comment]
This does not appear to be a regression in Moment.

I reproduced the setup across the relevant and current versions:

- Moment 2.22.2 with Jest 24: works
- Moment 2.29.1 with Jest 24: works
- The latest Moment 2.30.1 and moment-timezone 0.6.3 with Jest 30: works after updating the Jest API

The relevant change was in Jest 26, which removed the deprecated `require.requireActual` API. Replace:

```js
const actual = require.requireActual('moment');
```

with:

```js
const actual = jest.requireActual('moment');
```

The old form works with Jest 24 but fails with Jest 26 and later with:

```text
TypeError: require.requireActual is not a function
```

This Jest change was released in Jest 26.0.0 on May 4, 2020: https://github.com/jestjs/jest/pull/9854

With that one-line change, the example works with Moment 2.29.1 and the latest Moment release. Therefore, the setup did previously work, but its failure was caused by the Jest API removal rather than a change in Moment's timezone behavior.
