### ISSUE TITLE
TypeError moment__WEBPACK_IMPORTED_MODULE_7__ is not a function in v2.25.1

### ISSUE THREAD

**Issue by J1445** [moment/moment#5495]
Yesterday Had an issue with build process thankfully it was resolved instantly after upgrading to 2.5.1
**Describe the bug**
After updating to 2.5.1 from 2.5.0   Moment is not importing functions
` TypeError: moment__WEBPACK_IMPORTED_MODULE_7__ is not a function`
   

Code  implementation
```
import * as moment from 'moment';
fromDate = moment(from).format('MM/DD/YYYY')
vDate = moment(date, 'DD/MM/YYYY', true).format('MM/DD/YYYY');
toDate = moment(to).format('MM/DD/YYYY');
```

the import is compiled down to 
`var moment__WEBPACK_IMPORTED_MODULE_7__ = __webpack_require__(/*! moment */ "./node_modules/moment/src/moment.js");`

During Compilation 
Module not found: Error: Can't resolve './locale' in '/node_modules/moment/src/lib/locale'

**Comment by J1445** [comment]
reproducing steps npm install && npm start 

open browser localhost:4200 


[moment-issue.zip](https://github.com/moment/moment/files/4567917/moment-issue.zip)

**Comment by J1445** [comment]
Fixed in [Latest Commit](https://github.com/moment/moment/commit/1872bb22ff6cd19c56e7dc30c5765489d48e65f1)
