### ISSUE TITLE
Breaking changes in moment.d.ts type definition

### ISSUE THREAD

**Issue by nebez** [moment/moment#3617]
Updating the typings from 1.8 to 2.0 syntax ended up breaking my TypeScript 1.8 project.

I've reverted to 2.16.0 for now, but 2.17.0 will break any TypeScript < 2 projects.

**Comment by ichernev** [comment]
Cna you provide more info please.

**Comment by moreginger** [comment]
```
ERROR in /builds/*****/node_modules/moment/moment.d.ts
(251,28): error TS1110: Type expected.

ERROR in /builds/*****/node_modules/moment/moment.d.ts
(256,24): error TS1110: Type expected.

ERROR in /builds/*****/node_modules/moment/moment.d.ts
(392,98): error TS1110: Type expected.

ERROR in /builds/*****/node_modules/moment/moment.d.ts
(393,88): error TS1110: Type expected.

ERROR in /builds/*****/node_modules/moment/moment.d.ts
(635,80): error TS1110: Type expected.

ERROR in /builds/*****/node_modules/moment/moment.d.ts
(687,84): error TS1110: Type expected.

ERROR in /builds/*****/node_modules/moment/moment.d.ts
(688,84): error TS1110: Type expected.

ERROR in /builds/*****/node_modules/moment/moment.d.ts
(251,28): error TS2300: Duplicate identifier 'null'.

ERROR in /builds/*****/node_modules/moment/moment.d.ts
(256,24): error TS2300: Duplicate identifier 'null'.

ERROR in /builds/*****/node_modules/moment/moment.d.ts
(71,36): error TS2304: Cannot find name 'undefined'.

ERROR in /builds/*****/node_modules/moment/moment.d.ts
(251,28): error TS7008: Member 'null' implicitly has an 'any' type.

ERROR in /builds/*****/node_modules/moment/moment.d.ts
(256,24): error TS7008: Member 'null' implicitly has an 'any' type.

ERROR in /builds/*****/node_modules/moment/moment.d.ts
(392,98): error TS2362: The left-hand side of an arithmetic operation must be of type 'any', 'number' or an enum type.

ERROR in /builds/*****/node_modules/moment/moment.d.ts
(392,105): error TS2363: The right-hand side of an arithmetic operation must be of type 'any', 'number' or an enum type.

ERROR in /builds/*****/node_modules/moment/moment.d.ts
(393,88): error TS2362: The left-hand side of an arithmetic operation must be of type 'any', 'number' or an enum type.

ERROR in /builds/*****/node_modules/moment/moment.d.ts
(393,95): error TS2363: The right-hand side of an arithmetic operation must be of type 'any', 'number' or an enum type.

ERROR in /builds/*****/node_modules/moment/moment.d.ts
(635,45): error TS2371: A parameter initializer is only allowed in a function or constructor implementation.

ERROR in /builds/*****/node_modules/moment/moment.d.ts
(687,50): error TS2371: A parameter initializer is only allowed in a function or constructor implementation.

ERROR in /builds/*****/node_modules/moment/moment.d.ts
(688,50): error TS2371: A parameter initializer is only allowed in a function or constructor implementation.
```

**Comment by diegocasmo** [comment]
Same here

**Comment by ichernev** [comment]
@blakeembrey so they need to update?

**Comment by blakeembrey** [comment]
@ichernev I had noted in https://github.com/moment/moment/pull/3591#issuecomment-260131758 that using `undefined` was a breaking change for consumers, but perhaps it wasn't clear enough. It's a bit of a bummer because of the incompatibilities between versions makes it hard to update without affecting people.

@nebez @moreginger @diegocasmo What is preventing you from updating to 2.0?

**Comment by ghnz** [comment]
This one bit me because moment is a dependency of angular2-moment and was automatically updated for all our builds. This issue have been prevented if it was released as a 3.0 version instead of 2.17? 

When this issue first came to light yesterday I considered upgrading to typescript  2.0 but there were too many errors for us to resolve with our time constraints. I had to force our project to use 2.16.

**Comment by ichernev** [comment]
@blakeembrey well, why did we change it in the first place? Why not just keep the pre 2.0 stuff and keep going a few more months before moment 3.0?

**Comment by moreginger** [comment]
@blakeembrey yes, we will upgrade to typescript 2, but it's going to take a bit of effort.

For now we've pinned moment@2.16.*

**Comment by blakeembrey** [comment]
@ichernev It was changed in the PR I linked to. You're welcome to revert it, but it wasn't usable by people on 2.0 with `strictNullChecks` enabled. It's definitely nice to have `strictNullChecks` support, but for 1.8 compatibility you could revert all the `undefined` and `null` types. In the index signature position, you can use `Type | void` (using `void` instead of `undefined`) to achieve compatibility with both (it's a little hacky, but should work until you do 2.0 support).

FWIW, do you have a list of the errors when upgrading? It should be pretty straightforward, as far as I can recall it's only type system improvements in 2.0 and no major breaking changes. You don't have to share here as it'd clutter up the issue, but I'm happy to help if you need it.

**Comment by ichernev** [comment]
@blakeembrey so replace all the null/undefined in the current code with void, to make everyone happy? I actually added it to a few other necessary places. Then in moment 3.0 put back null/undefined.

By errors when upgrading -- I think only the funky one with the `[]`. But to be proper 2.0 strict as we discussed it needs a few more null/undefined added (which I did here: https://github.com/moment/moment/commit/2cfb22b779ed5c35dc590994715d73b6f650b74d)

**Comment by blakeembrey** [comment]
Yep, sounds good. `void` acts roughly like `undefined` where we'd need it for 1.8 and 2.0 compatibility. The index signature (I think the one you point to as `[]`) introduced in https://github.com/moment/moment/commit/d7390272ed18b62fec358ca98d3d9fa0ce8c5c05 can also go to `void`, the tests should catch if it's an issue in 2.0  but it should work fine.

**Comment by ichernev** [comment]
But it doesn't like the nulls
```
Running "exec:typescript-test" (exec) task
typing-tests/moment-tests.ts(25,8): error TS2345: Argument of type 'null' is not assignable to parameter of type 'MomentInput'.
typing-tests/moment-tests.ts(228,17): error TS2345: Argument of type 'null' is not assignable to parameter of type 'DurationInputArg1'.
typing-tests/moment-tests.ts(262,27): error TS2345: Argument of type 'null' is not assignable to parameter of type 'void | LocaleSpecification'.
typing-tests/moment-tests.ts(263,27): error TS2345: Argument of type 'null' is not assignable to parameter of type 'void | LocaleSpecification'.
typing-tests/moment-tests.ts(264,21): error TS2345: Argument of type 'null' is not assignable to parameter of type 'void | LocaleSpecification'.
```

I guess I can turn off strictNullChecks but that defeats the purpose ... maybe.

**Comment by blakeembrey** [comment]
@ichernev Correct, you'd have to ignore testing `null` for now. People using `strictNullChecks` won't be able to pass `null`, but it's probably not a huge drawback for them. If `undefined` is accepted, you can use `void` as a placeholder for now.

**Comment by ichernev** [comment]
@blakeembrey ok, here's a crazy idea -- why don't you release a patch 1.x version that supports both null and undefined, to be just allowed keywords but not really have any meaning. In 1.x you can't have strict null checks anyway so the data is worthless, but it will make the 1.x and 2.x formats compatible with each other. Then we can tell all complaining 1.x people to update to latest 1.x (which I hope is safe and easy, not like updating to 2.x).

**Comment by blakeembrey** [comment]
@ichernev I would love that, but unfortunately I am not a collaborator on TypeScript, just a contributor trying to help out like here. I would love the same thing, but note there are more types than just `null` and `undefined`. There are number and boolean literals as well. However, there was an issue to support something like this but I can't find it now. /cc @mhegazy @DanielRosenwasser.

**Comment by marwahaha** [comment]
How could we move forward with this?

**Comment by blakeembrey** [comment]
@marwahaha Release the TypeScript 2.x definitions with moment 3.0, or adopt a versioning scheme that is compatible with TypeScript users and give those users notice (e.g. mention that minors may introduce breaking TypeScript changes in the README). I believe the authors just need to decide whether the module will be 100% true to semver, or make some allowances to ensure that in the future the definition can be improved more freely.

**Comment by chrisleck** [comment]
The `null` issue is causing a problem for my project (using TS 2.4.*).  https://github.com/moment/moment/issues/4073

**Comment by Fundebug** [comment]
@nebez Installing moment 2.16.0 not working

```
bower install moment#2.16.0 --save
```

```
### Fast Compile >>client/typings/tsd.d.ts
Using tsc v1.7.5
/home/vagrant/Fundebug/funweb/client/bower_components/moment/moment.d.ts(5,26): error TS1110: Type expected.
/home/vagrant/Fundebug/funweb/client/bower_components/moment/moment.d.ts(6,22): error TS1110: Type expected.
/home/vagrant/Fundebug/funweb/client/bower_components/moment/moment.d.ts(7,28): error TS1110: Type expected.
/home/vagrant/Fundebug/funweb/client/bower_components/moment/moment.d.ts(282,7): error TS1110: Type expected.
/home/vagrant/Fundebug/funweb/client/bower_components/moment/moment.d.ts(290,5): error TS1128: Declaration or statement expected.
/home/vagrant/Fundebug/funweb/client/bower_components/moment/moment.d.ts(292,21): error TS1110: Type expected.
/home/vagrant/Fundebug/funweb/client/bower_components/moment/moment.d.ts(293,21): error TS1110: Type expected.
/home/vagrant/Fundebug/funweb/client/bower_components/moment/moment.d.ts(294,18): error TS1110: Type expected.
/home/vagrant/Fundebug/funweb/client/bower_components/moment/moment.d.ts(306,7): error TS1110: Type expected.
/home/vagrant/Fundebug/funweb/client/bower_components/moment/moment.d.ts(562,100): error TS1005: '=' expected.

>> 10 syntax errors
>> Error: tsc return code: 2
Warning: Task "ts:client" failed. Use --force to continue.

Aborted due to warnings.
```
