### ISSUE TITLE
Version 2.27.0 breaks FR locale parsing

### ISSUE THREAD

**Issue by apinsard** [moment/moment#5669]
**Describe the bug**
Upgrading from 2.26.0 to 2.27.0 breaks human dates parsing with accents in french.

**To Reproduce**
```
>> moment().format('D MMM YYYY')
"6 août 2020"
>> moment(moment().format('D MMM YYYY'), 'D MMM YYYY').isValid()
false
>> moment('6 août 2020', 'D MMM YYYY').isValid()
false
>> moment('6 aout 2020', 'D MMM YYYY').isValid()
true
>> moment('6 févr. 2020', 'D MMM YYYY').isValid()
false
>> moment('6 fevr. 2020', 'D MMM YYYY').isValid()
true
```

**Expected behavior**
`moment(human_date_with_accents, 'D MMM YYY')` should be valid, especially since `moment().format('D MMM YYYY')` returns a string with accents, it should be reversible. Just as previous version 2.26.0:

```
>> moment().format('D MMM YYYY')
"6 août 2020"
>> moment(moment().format('D MMM YYYY'), 'D MMM YYYY').isValid()
true
>> moment('6 août 2020', 'D MMM YYYY').isValid()
true
>> moment('6 aout 2020', 'D MMM YYYY').isValid()
true
>> moment('6 févr. 2020', 'D MMM YYYY').isValid()
true
>> moment('6 fevr. 2020', 'D MMM YYYY').isValid()
true
```

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04 / ChromeOS
 - Browser: Firefox / Chrome
 - Version: 79.0 / Unknown

**Moment-specific environment**

* Europe/Paris
* Any time since upgrading to 2.27.0 yesterday

```
Thu Aug 06 2020 13:01:18 GMT+0200 (Central European Summer Time)
06/08/2020, 13:01:18
-120
Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:79.0) Gecko/20100101 Firefox/79.0
2.27.0
```

**Additional context**
I suspect this is related to #4600 #5555

**Comment by kiwdahc** [comment]
I also use to use this import with typescript to get moment with included locales.
`import moment from 'moment/min/moment-with-locales.min.js'`

This now causes the following error when upgrading from 2.24.0 to 2.27.0.

`Cannot find module 'moment/min/moment-with-locales.min.js' or its corresponding type declarations.ts(2307)`


Is there some possible mistakes with the type declarations or is this auto included? I saw the change logs said it "might" be included but I am not sure what that means.

**Comment by marwahaha** [comment]
I could not reproduce this on 2.29.0 on the Moment.js website.
I think the accents are required to parse.

```
moment.locale('fr')
"fr"
moment('6 août 2020', 'D MMM YYYY').isValid()
true
moment('6 févr. 2020', 'D MMM YYYY').isValid()
true
moment('6 févr. 2020', 'D MMM YYYY').format()
"2020-02-06T00:00:00-08:00"
moment('6 août 2020', 'D MMM YYYY').format()
"2020-08-06T00:00:00-07:00"

moment().subtract(1, 'month').format('D MMM YYYY')
"23 août 2020"
moment(moment().subtract(1, 'month').format('D MMM YYYY'), 'D MMM YYYY').format()
"2020-08-23T00:00:00-07:00"
```
