### ISSUE TITLE
Moment.d.ts file compilation error

### ISSUE THREAD

**Issue by yesparthasarathy** [moment/moment#3618]
moment.d.ts file in version 2.17.0 is  not good, Its giving TS compilation error .

 interface MomentParsingFlags {
    empty: boolean;
    unusedTokens: string[];
    unusedInput: string[];
    overflow: number;
    charsLeftOver: number;
    nullInput: boolean;
    invalidMonth: string | null;
    invalidFormat: boolean;
    userInvalidated: boolean;
    iso: boolean;
    parsedDateParts: any[];
    meridiem: string | null;
  }

null causing the compile error. it works fine in 2.15.2 version. please check this out.

TypeScript error: /Users/pas9150/Main/NypHealth/node_modules/moment/moment.d.ts(251,28): Error TS1110: Type expected.
TypeScript error: /Users/pas9150/Main/NypHealth/node_modules/moment/moment.d.ts(256,24): Error TS1110: Type expected.
TypeScript error: /Users/pas9150/Main/NypHealth/node_modules/moment/moment.d.ts(392,98): Error TS1110: Type expected.
TypeScript error: /Users/pas9150/Main/NypHealth/node_modules/moment/moment.d.ts(393,88): Error TS1110: Type expected.
TypeScript error: /Users/pas9150/Main/NypHealth/node_modules/moment/moment.d.ts(635,80): Error TS1110: Type expected.
TypeScript error: /Users/pas9150/Main/NypHealth/node_modules/moment/moment.d.ts(687,84): Error TS1110: Type expected.
TypeScript error: /Users/pas9150/Main/NypHealth/node_modules/moment/moment.d.ts(688,84): Error TS1110: Type expected.

**Comment by faddee** [comment]
Same issue here...

```
C:\path\to\project\node_modules\moment\moment.d.ts
(635,80): error TS1110: Type expected.

C:\path\to\project\node_modules\moment\moment.d.ts
(687,84): error TS1110: Type expected.

C:\path\to\project\node_modules\moment\moment.d.ts
(688,84): error TS1110: Type expected.

C:\path\to\project\node_modules\moment\moment.d.ts
(251,28): error TS2300: Duplicate identifier 'null'.

C:\path\to\project\node_modules\moment\moment.d.ts
(256,24): error TS2300: Duplicate identifier 'null'.

C:\path\to\project\node_modules\moment\moment.d.ts
(71,36): error TS2304: Cannot find name 'undefined'.

C:\path\to\project\node_modules\moment\moment.d.ts
(251,28): error TS7008: Member 'null' implicitly has an 'any' type.

C:\path\to\project\node_modules\moment\moment.d.ts
(256,24): error TS7008: Member 'null' implicitly has an 'any' type.

C:\path\to\project\node_modules\moment\moment.d.ts
(392,98): error TS2362: The left-hand side of an arithmetic operation must be of type 'any', 'number' or an enum type.

C:\path\to\project\node_modules\moment\moment.d.ts
(392,105): error TS2363: The right-hand side of an arithmetic operation must be of type 'any', 'number' or an enum type.

C:\path\to\project\node_modules\moment\moment.d.ts
(393,88): error TS2362: The left-hand side of an arithmetic operation must be of type 'any', 'number' or an enum type.

C:\path\to\project\node_modules\moment\moment.d.ts
(393,95): error TS2363: The right-hand side of an arithmetic operation must be of type 'any', 'number' or an enum type.

C:\path\to\project\node_modules\moment\moment.d.ts
(635,45): error TS2371: A parameter initializer is only allowed in a function or constructor implementation.

C:\path\to\project\node_modules\moment\moment.d.ts
(687,50): error TS2371: A parameter initializer is only allowed in a function or constructor implementation.

C:\path\to\project\node_modules\moment\moment.d.ts
(688,50): error TS2371: A parameter initializer is only allowed in a function or constructor implementation.
```

**Comment by sbabeal** [comment]
same issue.  This is caused by the release made yesterday.  Please fix and issue a new release

**Comment by dogfoodsilo4** [comment]
Similar issues since moving to 2.17.0

Using tsc v1.8.10
../cs-data-access/node_modules/moment/moment.d.ts(251,28): error TS1110: Type expected.
../cs-data-access/node_modules/moment/moment.d.ts(256,24): error TS1110: Type expected.
../cs-data-access/node_modules/moment/moment.d.ts(392,98): error TS1110: Type expected.
../cs-data-access/node_modules/moment/moment.d.ts(393,88): error TS1110: Type expected.
../cs-data-access/node_modules/moment/moment.d.ts(635,80): error TS1110: Type expected.
../cs-data-access/node_modules/moment/moment.d.ts(687,84): error TS1110: Type expected.
../cs-data-access/node_modules/moment/moment.d.ts(688,84): error TS1110: Type expected.

**Comment by dogfoodsilo4** [comment]
Duplicate of #3617?

**Comment by rsinha25** [comment]
Same issue here when trying to compile jupyterlab (which has moment as a dep)

**Comment by marwahaha** [comment]
Duplicate of #3617 

TS 1.x typings should work in 2.18.1  :)

**Comment by Fundebug** [comment]
@marwahaha installing moment 2.18.1 not working:

```
 bower install moment#2.18.1 --save
``` 

error:

```
Using tsc v1.7.5
/home/vagrant/Fundebug/funweb/client/bower_components/moment/moment.d.ts(5,26): error TS1110: Type expected.
/home/vagrant/Fundebug/funweb/client/bower_components/moment/moment.d.ts(6,22): error TS1110: Type expected.
/home/vagrant/Fundebug/funweb/client/bower_components/moment/moment.d.ts(7,28): error TS1110: Type expected.
/home/vagrant/Fundebug/funweb/client/bower_components/moment/moment.d.ts(282,7): error TS1110: Type expected.
/home/vagrant/Fundebug/funweb/client/bower_components/moment/moment.d.ts(290,5): error TS1128: Declaration or statement expected.
/home/vagrant/Fundebug/funweb/client/bower_components/moment/moment.d.ts(292,21): error TS1110: Type expected.
/home/vagrant/Fundebug/funweb/client/bower_components/moment/moment.d.ts(293,21): error TS1110: Type expected.
/home/vagrant/Fundebug/funweb/client/bower_components/moment/moment.d.ts(294,18): error TS1110: Type expected.
/home/vagrant/Fundebug/funweb/client/bower_components/moment/moment.d.ts(306,7): error TS1110: Type expected.
/home/vagrant/Fundebug/funweb/client/bower_components/moment/moment.d.ts(566,100): error TS1005: '=' expected.

>> 10 syntax errors
>> Error: tsc return code: 2
Warning: Task "ts:client" failed. Use --force to continue.

Aborted due to warnings.
```
