### PR TITLE
[misc] typescript: Ensure moment.d.ts is tested for syntax

### PR DESCRIPTION
**Pull request by johnnyreilly**
as discussed in https://github.com/moment/moment/pull/3280 with @ichernev

These tests are triggered after the grunt test task. The basis of the tests were the DefinitelyTyped moment tests found [here](https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/moment).  Plugging this in revealed a few missing elements of the `moment.d.ts` Typing file.  I have added these in based on the definition in DT.

Hope this helps.

### CODE REVIEW

**Comment by johnnyreilly** [comment]
Took me a little while to realise how to get Travis to trigger the TypeScript test.  It does now.  There may well be a way to plug this testing into your grunt build; I'm afraid I don't know grunt though and so I can't help there.

**Comment by ichernev** [comment]
@johnnyreilly you need to add an exec that runs the tsc and then add that to https://github.com/moment/moment/blob/develop/Gruntfile.js#L198

Also I was hoping that it will run all our test cases under tsc and print warnings? Or this is too hard (or there are too many issues -- I guess from negative tests)?

**Comment by johnnyreilly** [comment]
Hi @ichernev,

Thanks for the exec pointers; I'll give it a try. I'm afraid.

> Also I was hoping that it will run all our test cases under tsc and print warnings? 

I don't think I entirely follow your intention. So I'll hedge my bets and say "yeah, too hard" 😉

**Comment by ichernev** [comment]
I meant -- maybe we can run the actual moment tests (there are many of them) against this thing, so it will actually get updated. I'm worried that now we have to keep adding stuff to the typing tests, that is independent from all other tests, and also independent of the documentation excerpts. So it will get out of sync, and become useless one day.

Well not too useless because now we check for the syntax of d.ts but that we can do with an empty test file.

**Comment by johnnyreilly** [comment]
Ah I see. I think the answer is no. Reason being that tsc is just a compiler. It's not a JavaScript runtime and so has no way to run tests. Remember the TypeScript "tests" are really just examples of API usage and their only way to fail is to fail to compile . So it would need to be independent I think.

**Comment by johnnyreilly** [comment]
An alternative approach would be to port your tests to TypeScript and plug into the existing runner. Then you could remove the TypeScript tests supplied as part of this pr in favour of them.

Is that something you'd be open to?

**Comment by johnnyreilly** [comment]
This would probably be the nicer approach but not having looked at your tests I'm not sure how much work it would involve.

**Comment by ichernev** [comment]
@johnnyreilly well, `typing-tests/moment-tests.ts` is no more typescript than the tests. You can have a look at `src/test/*/*.js`. I agree the file ending is different, but we can just trick it to "compile" it and not execute (because as you said it can't execute).

**Comment by johnnyreilly** [comment]
I'll take a look when I get a moment and report back.

**Comment by johnnyreilly** [comment]
Pun not actually intended

**Comment by johnnyreilly** [comment]
Hey @ichernev,

I've just moved to use the Gruntfile driven suggestion of yours.  I can't look at the running all tests together approach right now although I'll try to get time at some point.  Would you be interested in taking this PR in the interim?

**Comment by ichernev** [comment]
@johnnyreilly I can not get tsc command to work. I installed 1.5.3 and it tells me `error TS5023: Unknown compiler option 'moduleResolution'.` and according to https://github.com/axmor/typecs/issues/93 it should work with 1.5.0-beta

**Comment by johnnyreilly** [comment]
What version of TypeScript are you running? I'm on 1.8. I think that was added in 1.6.... http://www.typescriptlang.org/docs/handbook/compiler-options.html

**Comment by johnnyreilly** [comment]
Either way; it's not necessary and so I've removed it.  Want to try now?

**Comment by ichernev** [comment]
Merged in 6f3d87ae71ee938874e7d6fde8ccab4eb07efe42

**Comment by ichernev** [comment]
The main problem was that your implementation depended on a globally installed typescript, and I happened to install the wrong one (which worked half way but was old version so displayed some weird errors), so I just made sure to use the locally installed one -- https://github.com/moment/moment/commit/2c23c881070ffa5131e26372c3badc6dbf461092. Its now also run as part of the tests -- https://github.com/moment/moment/commit/12b4fc7f3a3076de60d8a5c0d9b3ccd05ca3bab7

**Comment by johnnyreilly** [comment]
Awesome - thanks!

**Comment by johnnyreilly** [comment]
Was it not run as part of the tests already?  Did the following code not include this in the test run?


`grunt.registerTask('test', ['test:node', 'test:typescript']);`

**Comment by ichernev** [comment]
But the default task did only `test:node`, now it does `test`.

**Comment by johnnyreilly** [comment]
Ah - I see.  Cheers.
