### PR TITLE
[critical] Revert require rename, fixes #4216

### LINKED ISSUE #4216: Webpack Error: Cannot find module "./locale" after updating to 2.19.0
**Edit: If you set your dependency to 2.18.1, everything will be fine. We are coordinating with some other libraries to find a permanent solution**
**Edit 2 : Set `"moment": "2.18.1"` in your package.json**
**Edit 3: We believe this is fixed.**

Hello. 
Using create-react-app. After updating moment to 2.19.0 i have this error on load : 

Error: Cannot find module "./locale"
-> 9 stack frames were collapsed.
./src/utils/Utils.js
src/utils/Utils.js:1
> 1 | import moment from 'moment'

### PR DESCRIPTION
**Pull request by ichernev**
Changes introduced in #4213 and #4214 broke webpack -- #4216. Reverting them

### CODE REVIEW

**Comment by ichernev** [comment]
Merged in 43a226e10dc5634bf144c8eaf91f3de39698876a
